[tool.poetry]
name = "tests-api-methods"
version = "0.1.0"
description = ""
authors = ["Oksana Bondareva <xanka359@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
